title: Mikaela Rosen
url: "https://rosenm.github.io/"
baseurl: ""
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://rosenm.github.io/"
footer_text: "Page design by ankitsultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Research"
    link: "/research"
  - name: "Activities"
    link: "/activities"
  - name: "SciComm"
    link: "/scicomm"
  - name: "Life outtakes"
    link: "/beyond-research"
